server:
  port: 8081   # catalog-service

spring:
  application:
    name: catalog-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/catalog_db}
    username: ${SPRING_DATASOURCE_USERNAME:catalog_user}
    password: ${SPRING_DATASOURCE_PASSWORD:catalog_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'

  jpa:
    hibernate:
      ddl-auto: update   # let hibernate sync schema after SQL runs
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
